sap-order-to-cash:
  outputs:
    dev:
      catalog: sap_order_to_cash
      host: adb-540853645307037.17.azuredatabricks.net
      http_path: /sql/1.0/warehouses/5d55c72f37174cec
      schema: default
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
